### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by mtrippodi** [bramstroker/zf2-fullpage-cache#34]
Hi,
not sure wether a real issue or I'm doing something wrong:

```
 php public/index.php strokercache clear route_home
```

has no effect. Cache is not invalidated even though console message says "Cache invalidation succeeded".
Please help.
Thanks, also for this great module!

**Comment by vali82** [comment]
I have the same problem... please help!

**Comment by bramstroker** [comment]
Thanks for reporting. I'm very busy lately. Will try to look into it this week.

**Comment by bramstroker** [comment]
Please drop your full cache configuration (storage adapter) in a comment.

**Comment by vali82** [comment]
I didn't change ca module.config.php from your module... only the strokercache.local.php:
return array(
    'strokercache' => array(
        'strategies' => array(
            'enabled' => array(
                'StrokerCache\Strategy\RouteName' => array(
                    'routes' => array(
                        'home',
                    ),
                ),
            ),
        )
    )
);

**Comment by vali82** [comment]
I called the clearByTags() method and the cache is removed. 
$stokerCacheService = $this->getServiceLocator()->get('strokercache_service');
$stokerCacheService->clearByTags(['route_home']);

cool module;)

**Comment by bramstroker** [comment]
@vali82 
The code you provided is exactly what should a executed by the console controller. You sure it doesn't work when you call it from the CLI?

**Comment by vali82** [comment]
yes, I'm pretty sure it does not work in console ...
recommendation :
1. maybe you implement caching routes depending on the user logged in
2. cacheing specifying the controller action

**Comment by dgram** [comment]
i have the same problem when using APC as cache adapter, after a review of the code i found the "problem" - your clearByTags function always return false without clearing the item if adapter isnt of type TaggableInterface.

I think this should be documented

regards

**Comment by coffeecore** [comment]
Hi !

I have some problems with clearByTags, but, if you add `true` in `return $this->getCacheStorage()->clearByTags($tags, true);`in the CacheService.php, it looks good

Regards

**Comment by bramstroker** [comment]
dgram Nice catch! I think it would be a good idea to throw a custom exception when the adapter doesn't implement `TaggableInterface` instead of returning false. Then we can catch the exception in the console controller and display a descriptive message to the user. What do you think?

**Comment by bramstroker** [comment]
This is implemented in the latest version.
The console command show a message now when you try to purge tags on an storage adapter which doesn't support it.
