### ISSUE TITLE
Redis adapter

### ISSUE THREAD

**Issue by YP28** [bramstroker/zf2-fullpage-cache#35]
Hi,

First, I'd like to inform you that the Zend Redis adapter doesn't seem to be working, more about that in this exception message:
``` php
Fatal error: Uncaught exception 'Zend\Cache\Exception\RuntimeException' with message 'No resource with id 'default'' in /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Adapter/RedisResourceManager.php:114 Stack trace: #0 /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Adapter/Redis.php(100): Zend\Cache\Storage\Adapter\RedisResourceManager->getResource('default') #1 /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Adapter/Redis.php(203): Zend\Cache\Storage\Adapter\Redis->getRedisResource() #2 /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Adapter/AbstractAdapter.php(474): Zend\Cache\Storage\Adapter\Redis->internalHasItem('4b208041ee263d8...') #3 /var/www/html/beste/vendor/stroker/cache/src/StrokerCache/Service/CacheService.php(66): Zend\Cache\Storage\Adapter\AbstractAdapter->hasItem('4b208041ee263d8...') #4 /var/www/html/beste/vendor/stroker/cache/src/StrokerCache/Listener/CacheListener.ph in /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Adapter/RedisResourceManager.php on line 114
```

Secondly, I cannot find any option to set the TTL. Did I miss anything? Is it just not documented or is the option just missing in the module?

Yordi

**Comment by bramstroker** [comment]
Hi Yordi,

This looks like a problem with your setup (redis settings) or a bug with the ZF2 Redis storage adapter. I don't have any hands on experience with Redis, so I don't know what causes the error. In my module I'm just utilizing the `StorageFactory` provided with ZF2.

Did you try to construct a redis adapter in your application without using my module? i.e.

    $cache = StorageFactory::factory(array(
        'adapter' => array (
                    'name' => 'redis',
                    'options' => array (
                            'server' => [
                                    'host' => '127.0.0.1',
                                    'port' => 6379,
                            ]
                    )
            ),
    ));
    $cache->setItem('test', 'foo');
    var_dump($cache->getItem('test'));

You can set the ttl by adding the ttl key to the options array. See http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html#basic-configuration-options

Hope this helps
