### ISSUE TITLE
Is it possible to disable caching with some option?

### ISSUE THREAD

**Issue by svycka** [bramstroker/zf2-fullpage-cache#51]
I would like to disable cache in development but want it enabled by default now. As I understand now it is recommended to add it in `cache.local.php` but the problem is this is configured only after deployment I would like to rename this to `cache.global.php` and in development disable cache in `cache.local.php` or something. 
Guess I could work around this with event manager somehow attaching to events and disabling caching but maybe there is a built-in mechanism like dummy storage, `enabled/disabled` flag or something? if not maybe would be a good idea to add?

**Comment by bramstroker** [comment]
Good idea. I just tagged a new version 2.0.1.
Fixed by https://github.com/bramstroker/zf2-fullpage-cache/pull/52
You can put `'enabled' => false` in your config.. see the docs

**Comment by svycka** [comment]
thanks will try

**Comment by svycka** [comment]
just a note this is a new feature and if you name your versions as described here http://semver.org/ that's what composer recommends, the release should be 2.1.0 not 2.0.1 as this is not a bugfix.

again thanks for so fast response :D

**Comment by bramstroker** [comment]
Yes you are right. The release should be 2.1.0 not 2.0.1
I'll remove the tag and create 2.1.0 when your other PR's are merged.

**Comment by svycka** [comment]
NO! please don nott remove!

**Comment by bramstroker** [comment]
I agree, will leave the 2.0.1 tag as there can be people depending on it already now.
