### ISSUE TITLE
Using StrokerCache with Zend\Session\SaveHandler\DbTableGateway in ZF3

### ISSUE THREAD

**Issue by jonathanmaron** [bramstroker/zf2-fullpage-cache#57]
In a ZF3 application, when I load StrokerCache in the modules config array, the database save handler, which I set in the Module.php, is null in the Zend\Session\SessionManager. When StrokerCache is NOT loaded, the database save handler is Zend\Session\SaveHandler\DbTableGateway, as configured.

Here are some details.

In Module::onBootstrap(MvcEvent $event), I set the database save hander as follows:

    use Zend\Db\Adapter\AdapterInterface;
    use Zend\Db\TableGateway\TableGateway;
    use Zend\Session\SaveHandler\DbTableGateway;
    use Zend\Session\SaveHandler\DbTableGatewayOptions;
    use Zend\Session\SessionManager;

    // [..]

    $sm = $event->getApplication()->getServiceManager();

    $config  = $sm->get('Config');
    $adapter = $sm->get(AdapterInterface::class);

    $tableGateway = new TableGateway('sessions', $adapter);
    $saveHandler  = new DbTableGateway($tableGateway, new DbTableGatewayOptions());
    $manager      = $sm->get(SessionManager::class);
    $manager->setSaveHandler($saveHandler);

However, in my Factories, when I access SessionManager::class, like this:

    $sessionManager = $container->get(SessionManager::class);
    $sessionManager->getSaveHandler();

only "null" is returned by getSaveHandler() when StrokerCache is loaded, and "Zend\Session\SaveHandler\DbTableGateway" when StrokerCache is not loaded.

Consequently, session data is written to the file system (default behavior) when StrokerCache is loaded and not to the database, as required. The other session config options are available via SessionManager::class, just the crucial save handler is not set.

Would you have any ideas why this should be? Any pointers would be very gratefully accepted. Thank you kindly.

**Comment by bramstroker** [comment]
I have no clue. StrokerCache uses it's own service aliases and factories and should not conflict with your mentioned code in any way.

When this lines are executed:
    $manager      = $sm->get(SessionManager::class);
    $manager->setSaveHandler($saveHandler);

And later in your application flow:
    $sessionManager = $container->get(SessionManager::class);
    $sessionManager->getSaveHandler();

Than the result should be a be an instance of `DbTableGateway`

I can think of 2 ways the above assumption won't be true:

- onBootstrap() of your mentioned module is never called
- `setSaveHandler()` is called a second time with a null instance

You should use a debugger and put some breakpoints on those places to see what happens.

Also you could try with the ZF3 skeleton and only strokerCache module. When the issue also exists in this case I can have a look next week.

**Comment by jonathanmaron** [comment]
First of all, I checked your two assumptions. The onBootstrap() method was being called, and the setSaveHandler() method was being called only once.

Following that, I installed the skeleton application as you suggested and was indeed able to reproduce the problem.

However, I did find the problem, and the fix, which I believe has nothing to do with StrokerCache.

The solution is as follows:

In the config file at key "['service_manager']['factories']", it is possible to define the custom save handler using the key:

    \Zend\Session\SaveHandler\SaveHandlerInterface::class

I personally cannot find this described in the Zend\Session documentation, however, I did find it described in the [source code](https://github.com/zendframework/zend-session/blob/master/src/Service/SessionManagerFactory.php#L42).

Once I had created another Factory to instantiate the save handler:

    namespace Application\Session\SaveHandler;

    use Interop\Container\ContainerInterface;
    use Zend\Db\Adapter\Adapter;
    use Zend\Db\TableGateway\TableGateway;
    use Zend\ServiceManager\Factory\FactoryInterface;
    use Zend\Session\SaveHandler\DbTableGateway;
    use Zend\Session\SaveHandler\DbTableGatewayOptions;

    class Factory implements FactoryInterface
    {
        public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
        {
            $config  = $container->get('Config');
            $adapter = $container->get(Adapter::class);

            $tableGateway = new TableGateway('sessions', $adapter);
            $saveHandler  = new DbTableGateway($tableGateway, new DbTableGatewayOptions());

            return $saveHandler;
        }
    }

And set it at the specified the key

    $config['service_manager']['factories'][\Zend\Session\SaveHandler\SaveHandlerInterface::class] => \Application\Session\SaveHandler\Factory::class

And removed the code from the Module::onBootstrap(MvcEvent $event) (see original post), both the correctly configured SessionManager and StrokerCache work as expected.

Case closed.
